export interface ThemeInterface {
  container?: object,
  viewWrapper?: object,
  mainMenuLogo?: object,
  mainMenuButton?: object,
  mainMenuButtonText?: object,
  mainMenuIconWrapper?: object,
  mainMenuIconLink?: object,
  mainMenuIconImg?: object,
  mainMenuLeftWeb?: object,
  mainMenuRightWeb?: object,
  mainMenuWebImg?: object,
  axisPad?: object,
  axisPadHandler?: object,
  gameControlsBottomRow?: object,
  gameControlsButton?: object,
  gameControlsButtonImg?: object,
  gameControlsTopRow?: object,
  gameBackgroundImg?: object,
  gameCanvas?: object,
  gameControls?: object,
  gameEngine?: object,
  gameWrapper?: object
}